services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    container_name: rcrs-server
    volumes:
      - ./rcrs-server/launch-server.sh:/scripts/launch-server.sh:ro
      - ./rcrs-server/custom-maps:/app/rcrs-server/custom-maps:ro
      - ./results:/app/results
      - shared_data:/app/shared
    environment:
      - EXPERIMENT_NAME
      - MAP_NAME
      - RUN_TYPE
    command: >
      bash -c "/scripts/launch-server.sh"

  agent-sample:
    depends_on:
      - server
    build:
      context: .
      dockerfile: Dockerfile
      target: agent-sample
    container_name: rcrs-agent-sample
    volumes:
      - ./rcrs-agent/launch-agent.sh:/scripts/launch-agent.sh:ro
      - ./results:/app/results
      - shared_data:/app/shared
    environment:
      - EXPERIMENT_NAME
      - RUN_TYPE
    command: >
      bash -c "/scripts/launch-agent.sh"

  agent-custom:
    depends_on:
      - server
    build:
      context: .
      dockerfile: Dockerfile
      target: agent-custom
    container_name: rcrs-agent-custom
    volumes:
      - ./rcrs-agent/launch-agent.sh:/scripts/launch-agent.sh:ro
      - ./results:/app/results
      - shared_data:/app/shared
      - ../ait-rescue:/app/rcrs-agent
    environment:
      - EXPERIMENT_NAME
      - RUN_TYPE
    command: >
      bash -c "/scripts/launch-agent.sh"

  ringo:
    build:
      context: .
      dockerfile: Dockerfile
      target: ringo
    container_name: ringo-viewer
    volumes:
      - ./results:/app/results:ro
      - ./ringo-viewer/launch-ringo.sh:/scripts/launch-ringo.sh:ro
    environment:
      - EXPERIMENT_NAME
    ports:
      - "3000:3000"
    command: >
      bash -c "/scripts/launch-ringo.sh"

volumes:
  shared_data:
